### ISSUE TITLE
Feature: Sync metadata - file attributes

### ISSUE THREAD

**Issue by am11** [OneDrive/onedrive-explorer-win#1]
Would be really useful if OneDrive sync the associated file attributes such as; hidden and read-only flags (at least these basic ones), and expose it to the API as well.

Currently, if you have a read-only or hidden file on a device, after syncing it loses those attributes on the other (except for the timestamp).

**Comment by rgregg** [comment]
OneDrive doesn't support / have a concept of read-only or hidden files which is why those bits are striped when the sync client uploads files. I'd suggest posting this request on [onedrive.uservoice.com](http://onedrive.uservoice.com) since that's where the Sync team is hanging out and looking at feedback.

**Comment by am11** [comment]
Oh sorry! Thanks for the link. :+1: 

I have submitted the feedback there: http://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7142918-feature-sync-metadata-file-attributes. :smiley:
