### ISSUE TITLE
Upload Large File with Error

### ISSUE THREAD

**Issue by WeidongShen** [OneDrive/onedrive-explorer-win#5]
When I tried to upload a large file more than 100M with the "Upload" -> "Large File" menu option, I get the following error:

OneDrive reported the following error:
code:
message: Exception of type 'OneDrive.ODServerException' was thrown.
{
  "error": {
    "code": "invalidRequest",
    "message": "Invalid API or resource",
    "innererror": {
    "code": "generalException"
    }
  }
}

**Comment by rgregg** [comment]
Hi @WeidongShen the issue here is a bug in the explorer. When you upload a large file to a subfolder in OneDrive, the Path dialog that appears pre-populates with a value like "/drive/root:/Documents/folder/file.bin" which is the wrong format. I've pushed a change just now that will change the default to what it should have been, which is "/Documents/folder/file.bin". If you fix the path in the dialog to remove the `/drive/root:` or if you pull down my changes, this issue should be resolved.

Let me know if that resolves this issue for you.
