### ISSUE TITLE
How to Authenticate with the new OneDrive API for Windows Store App?

### ISSUE THREAD

**Issue by WeidongShen** [OneDrive/onedrive-explorer-win#6]
Is it possible to add a sample on how to authenticate with the new OneDrive API for Windows Store App? Thanks!

**Comment by rgregg** [comment]
The code in [this Gist](https://gist.github.com/rgregg/0f45cebbfbde4b7e4157) provides details on how to authenticate with a Windows Store app using single sign-in. You can use this class with the OneDriveSDK from this project to sign-in and call the OneDrive API.

To use this method, you will need to have your project associated with an app in the store. Otherwise the calls to get an access token will fail.

**Comment by casaout** [comment]
I want to be able to import & export files from my app to my OneDrive folder. However, I don't want to release the app, as it will just be used for internal use. Does this mean that I can't do this using the OneDrive API? Are there any other possibilities? Thanks.

**Comment by rgregg** [comment]
@casaout You can implement the web-based OAuth flow in a web view just like the example in Windows forms does. You can also just register your app with the Windows Store to get a unique identifier but then not release the app.
